name: khatoon_container
description: "khatoon application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^9.2.0
  dio: ^5.9.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  json_annotation: ^4.9.0
  decimal: ^3.2.4
  # analyzer: ^9.0.0 <-- این خط را حذف کنید
  isar: ^3.1.0+1 # یا 4.0.0-dev.10 اگر می‌خواهید نگه دارید
  path_provider: ^2.1.5
  isar_flutter_libs: ^3.1.0+1
  build: 2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  source_gen: ^1.2.2 # برای سازگاری با isar_generator
  dart_style: ^2.2.3
  flutter_lints: ^6.0.0
  isar_generator: ^3.1.0+1 # مطمئن شوید نسخه آن با isar همخوانی دارد
  json_serializable: ^6.8.0